spring:
  application:
    name: edi_thoth_server3
 
server:
  port: 9003
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://10.10.12.27:9001/eureka/,http://10.10.12.27:9002/eureka/,http://10.10.12.27:9003/eureka/