spring:
  application:
    name: edi_thoth_server
server:
  port: 9001
eureka:
#  server:
#    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://10.10.12.27:9001/eureka/,http://10.10.12.27:9002/eureka/,http://10.10.12.27:9003/eureka/
info:
  contact:
    appName: edi_thoth_server

---
spring:
  profiles: s2
server:
  port: 9002
---
spring:
  profiles: s3
server:
  port: 9003