info:
  contact:
    appName: edi_thoth_config
    author: atliwen

gitpassword: qq123123

spring:
  application:
    name: edi_thoth_config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/atliwen/SpringCloudProject
          search-paths:
            - edi-thoth-parent/config-repo
          username: 499014099@qq.com
          password: ${gitpassword}
server:
  port: 9004

#spring.profiles.active
eureka:
  instance:
#    lease-expiration-duration-in-seconds: 2
#    lease-renewal-interval-in-seconds: 1
    hostname: edithothconfig
  client:
    serviceUrl:
      defaultZone: http://edithothserver:9001/eureka/
---
spring:
  profiles: c2
server:
  port: 9005
---
spring:
  profiles: c3
server:
  port: 9006