info:
  contact:
    appName: edi_thoth_config
    author: atliwen

spring:
  application:
    name: edi_thoth_config
  cloud:
    config:
      server:
        svn:
          uri: http://10.10.6.55/edi/edithothparent/
          username: 李文
          password: liwen1122
          default-label: configrepo
  profiles:
    active: subversion
#        git:
#          uri: https://github.com/atliwen/SpringCloudProject
#          search-paths:
#            - edi-thoth-parent/config-repo
#          username: 499014099@qq.com
#          password: qqqqq

server:
  port: 9004

#spring.profiles.active

eureka:
  client:
    serviceUrl:
      defaultZone: http://edithothserver:9001/eureka/
  instance:
    hostname: edithothconfig
