server:
  port: 9009

spring:
  application:
    name: client-OrderServer

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://10.10.12.27:9001/eureka/,http://10.10.12.27:9002/eureka/,http://10.10.12.27:9003/eureka/
---
spring:
  profiles: c2
server:
  port: 9010
---
spring:
  profiles: c3
server:
  port: 9011