spring:
  application:
    name: edi_thoth_server
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://edithothserver:9001/eureka/
  instance:
    hostname: edithothserver
info:
  contact:
    appName: edi_thoth_server
    author: atliwen




