zuul:
  routes: 
    api-a-url: 
      path: /api-a/**
      service-id: client-server
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.12.27:9001/eureka/,http://10.10.12.27:9002/eureka/,http://10.10.12.27:9003/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1 